name: Build Sing-box Rule-set and Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  build_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download Sing-box
        run: |
          SING_BOX_VERSION="1.12.4"
          curl -Lo sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v${SING_BOX_VERSION}/sing-box-${SING_BOX_VERSION}-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          mv sing-box-*/sing-box ./sing-box
          chmod +x ./sing-box

      - name: Download JSON Rule-set
        run: |
          curl -Lo AWAvenue-Ads-Rule-Singbox.json https://github.com/TG-Twilight/AWAvenue-Ads-Rule/raw/refs/heads/main/Filters/AWAvenue-Ads-Rule-Singbox.json
      
      - name: Compile to SRS
        run: |
          ./sing-box rule-set compile --output AWAvenue-Ads-Rule-Singbox.srs AWAvenue-Ads-Rule-Singbox.json
      
      - name: Configure Git and Move File
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          mkdir -p rule
          
          mv AWAvenue-Ads-Rule-Singbox.srs rule/AWAvenue-Ads-Rule-Singbox.srs

      - name: Add, Commit and Push
        run: |
          if [ -n "$(git status --porcelain rule/)" ]; then
            git add rule/AWAvenue-Ads-Rule-Singbox.srs
            git commit -m "feat: Auto-build and update Sing-box rule-set"
            git push
          else
            echo "No changes to commit. Skipping push."
          fi
